// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNbCr4uI_hL7UO_rWaFq6HV5P_sFEIrcY',
    appId: '1:102533466026:web:949ff38a092df97ef18dd3',
    messagingSenderId: '102533466026',
    projectId: 'illsan-job',
    authDomain: 'illsan-job.firebaseapp.com',
    storageBucket: 'illsan-job.firebasestorage.app',
    measurementId: 'G-ZH7RGZJ1VV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPiyOHOuxHKi3CsafkvZan3m1qn-Y1yRM',
    appId: '1:102533466026:android:3f968ef0eff2aee9f18dd3',
    messagingSenderId: '102533466026',
    projectId: 'illsan-job',
    storageBucket: 'illsan-job.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNb1_LopWc36aJdd92nmG6B4Q_W6qve60',
    appId: '1:102533466026:ios:4e3c3c5f51c94fdbf18dd3',
    messagingSenderId: '102533466026',
    projectId: 'illsan-job',
    storageBucket: 'illsan-job.firebasestorage.app',
    iosBundleId: 'com.example.illsanJob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNb1_LopWc36aJdd92nmG6B4Q_W6qve60',
    appId: '1:102533466026:ios:4e3c3c5f51c94fdbf18dd3',
    messagingSenderId: '102533466026',
    projectId: 'illsan-job',
    storageBucket: 'illsan-job.firebasestorage.app',
    iosBundleId: 'com.example.illsanJob',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNbCr4uI_hL7UO_rWaFq6HV5P_sFEIrcY',
    appId: '1:102533466026:web:cabe72eb9db5c8bef18dd3',
    messagingSenderId: '102533466026',
    projectId: 'illsan-job',
    authDomain: 'illsan-job.firebaseapp.com',
    storageBucket: 'illsan-job.firebasestorage.app',
    measurementId: 'G-MWH9413GM9',
  );

}